name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 缓存 Buildozer 的依赖和 SDK
    - name: Cache Buildozer
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
          ~/.local/share/android
        key: ${{ runner.os }}-buildozer-${{ hashFiles('**/requirements.txt') }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev git \
        libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
        libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
        default-jdk unzip

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer kivy

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: OvertimeTracker-apk
        path: bin/*.apk
